services:
  vanessa-vod:
    build: .
    container_name: vanessa-vod
    init: true
    ports:
      - "8608:8608"
    environment:
      - DATA_DIR=/app/downloads/.appdata
    volumes:
      - "/vol00/WDC WD20SDZW-11Z3CS0_1/vod_downloads:/app/downloads"
      - ./logs:/app/logs
    restart: unless-stopped
